#aaaaaaaaaaaaa

name: main_test
env : 
  APPLICATION_NAME : "Name"
  PACKAGE_NAME     : "flasek-deploy-version-${{ github.sha }}"
  
on: 
  push:
    branches: 
      - master

jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "print hello test"
        run : echo "Hello test"
      
      - name : execute commands test
        run  : |
          echo "APPLICATION_NAME : ${{ env.APPLICATION_NAME }}"
          echo "PACKAGE_NAME : ${{ env.PACKAGE_NAME }}"
          
      - name: "git clone repo"
        uses: actions/checkout@v1
        
      - name: "print directory"
        run : ls -la
  
  my_build:
     runs-on: ubuntu-latest
     needs : [my_test]
     steps:
      - name: "print hello build"
        run : echo "Hello build"
      
      - name : execute commands build
        run  : |
          echo "APPLICATION_NAME : ${{ env.APPLICATION_NAME }}"
          echo "PACKAGE_NAME : ${{ env.PACKAGE_NAME }}"
          
          
      - name: "git clone repo"
        uses: actions/checkout@v1
        
      - name: "print directory"
        run : ls -la
